### ISSUE TITLE
Images downloaded look like gray.

### ISSUE THREAD

**Issue by Cuzyoung** [IGNF/FLAIR-1#10]
I encounter some confusion when I try to use Flair #1 dataset. I downloaded the data from the official website (Aerial images-train and test), and I found that the images in these two zip files look gray.
![viewfile](https://github.com/IGNF/FLAIR-1/assets/96894827/fbbac983-ee4e-4519-9c9d-ce358db5dbee)
![viewfile](https://github.com/IGNF/FLAIR-1/assets/96894827/d1d89e64-4548-4741-9fd1-4c2d20187744)
However, I found that the images are RGB with colors in other papers. So I hope to know if there are any problems with my download process.
![viewfile](https://github.com/IGNF/FLAIR-1/assets/96894827/8ce7c90a-9ad7-4faf-9dce-3e0891a48cd9)
I would appreciate it if you could answer my doubts. Looking forward to your reply!

**Comment by agarioud** [comment]
Hello @Cuzyoung,
The downloaded aerial images should have 5 channels : red - green - blue - infrared - elevation
They might look gray depending on the viewer you are using. 
Have you tried opening one with a software allowing band selection such as QGIS ?

**Comment by Cuzyoung** [comment]
Thanks for your timely response and sorry for my late response!!! I have turned tif images into RGB.
