### ISSUE TITLE
does the image label overlap?

### ISSUE THREAD

**Issue by Roberyan** [IGNF/FLAIR-1#11]
I wonder if different labels can have overlapping? Original label is given all 18 channels, I doubt if every image has all the labels involve, and if different labels can point to a same pixel?

**Comment by agarioud** [comment]
Hello @Roberyan ,
All labels have been annotated with the same nomenclature of 18(+1) classes, without any overlapping or hierarchical notion. Each pixel has a single annotation. 
A detailed semantic description of the classes is available in the appendix (page 16) here : https://arxiv.org/pdf/2310.13336v1
Hope this helps!

**Comment by Cuzyoung** [comment]
Hello @Roberyan ,
You are right. Not every image contains all 18 labels and you also can map different labels to the same pixel, such as mapping 13,14,15,16,17,18,19 classes into 13.

**Comment by Roberyan** [comment]
thanks for your help!
